DO NOT MERGE: workaround to build huaweigeneric-ril
This temporary change is to avoid building errors
due to new functions declarations.

error: 'dispatchSIM_APDU' undeclared here (not in a function)

huaweigeneric-ril 1.0.0.8 may be missing some of those,
or there is a problem in the symbols seen by huaweigeneric-ril.